In [8]:
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
#sentences
sent = ["the glass of milk",
       "the glass of juice",
       "the cup of tea",
       "I am a good boy",
       "I am a good developer",
       "understand the meaning of words",
       "your videos are good"]

In [15]:
#vocabulary_size
voc_size=10000

### One-Hot Representation

In [16]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[2575, 7121, 7736, 6313], [2575, 7121, 7736, 9676], [2575, 759, 7736, 5911], [7184, 3309, 9484, 2191, 149], [7184, 3309, 9484, 2191, 4962], [8552, 2575, 2891, 7736, 6923], [8203, 6511, 4993, 2191]]


### Word Embedding representation

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [17]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2575 7121 7736 6313]
 [   0    0    0    0 2575 7121 7736 9676]
 [   0    0    0    0 2575  759 7736 5911]
 [   0    0    0 7184 3309 9484 2191  149]
 [   0    0    0 7184 3309 9484 2191 4962]
 [   0    0    0 8552 2575 2891 7736 6923]
 [   0    0    0    0 8203 6511 4993 2191]]


In [18]:
dim = 15

In [19]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile(optimizer="adam", loss="mse")

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

array([[[ 0.04990096, -0.00515012,  0.0474975 , -0.017805  ,
         -0.03311371,  0.01563153,  0.00710887,  0.03070053,
         -0.04182167, -0.00975413],
        [ 0.04990096, -0.00515012,  0.0474975 , -0.017805  ,
         -0.03311371,  0.01563153,  0.00710887,  0.03070053,
         -0.04182167, -0.00975413],
        [ 0.04990096, -0.00515012,  0.0474975 , -0.017805  ,
         -0.03311371,  0.01563153,  0.00710887,  0.03070053,
         -0.04182167, -0.00975413],
        [ 0.04990096, -0.00515012,  0.0474975 , -0.017805  ,
         -0.03311371,  0.01563153,  0.00710887,  0.03070053,
         -0.04182167, -0.00975413],
        [ 0.04108595,  0.00041034,  0.04883608,  0.02095428,
         -0.02690262, -0.00307258,  0.04337389, -0.01601336,
         -0.01688173,  0.01297842],
        [-0.045576  ,  0.04825789, -0.01265182, -0.04956161,
         -0.02072117, -0.02895714, -0.03907393,  0.00237132,
         -0.03221591,  0.04796399],
        [-0.03649952,  0.01419343,  0.047622  ,  0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 2575, 7121, 7736, 6313])

In [23]:
model.predict(embedded_docs)[0]

array([[ 0.04990096, -0.00515012,  0.0474975 , -0.017805  , -0.03311371,
         0.01563153,  0.00710887,  0.03070053, -0.04182167, -0.00975413],
       [ 0.04990096, -0.00515012,  0.0474975 , -0.017805  , -0.03311371,
         0.01563153,  0.00710887,  0.03070053, -0.04182167, -0.00975413],
       [ 0.04990096, -0.00515012,  0.0474975 , -0.017805  , -0.03311371,
         0.01563153,  0.00710887,  0.03070053, -0.04182167, -0.00975413],
       [ 0.04990096, -0.00515012,  0.0474975 , -0.017805  , -0.03311371,
         0.01563153,  0.00710887,  0.03070053, -0.04182167, -0.00975413],
       [ 0.04108595,  0.00041034,  0.04883608,  0.02095428, -0.02690262,
        -0.00307258,  0.04337389, -0.01601336, -0.01688173,  0.01297842],
       [-0.045576  ,  0.04825789, -0.01265182, -0.04956161, -0.02072117,
        -0.02895714, -0.03907393,  0.00237132, -0.03221591,  0.04796399],
       [-0.03649952,  0.01419343,  0.047622  ,  0.03917587,  0.01664931,
         0.04777614, -0.02101094,  0.04247664